export default {
  notfound: "/assets/images/404.svg",
  logo: "/vercel.svg",
  logo_img: "/assets/images/logo_img.png",
  ftr_logo: "/assets/images/ftr_logo.svg",
  headLogo: "/assets/images/headLogo.svg",
  developerImg: "/assets/images/developerImg.png",
  topRectangle: "/assets/images/topRectangle.png",
  leftRectangle: "/assets/images/leftRectangle.png",
  project1: "/assets/images/project1.png",
  project2: "/assets/images/project2.png",
  project3: "/assets/images/project3.png",
  project4: "/assets/images/project4.png",
  myworksImg1: "/assets/images/myworksImg1.png",
  myworksImg2: "/assets/images/myworksImg2.png",
  myworksImg3: "/assets/images/myworksImg3.png",
  myworksImg4: "/assets/images/myworksImg4.png",
  myworksImg5: "/assets/images/myworksImg5.png",
  myworksImg6: "/assets/images/myworksImg6.png",
  myworksImg7: "/assets/images/myworksImg7.png",
  myworksImg8: "/assets/images/myworksImg8.png",
};
